[package]
name = "assembler"
version = "0.1.0"
authors = ["Nikita Antonenkov <krigar1184@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.3"
bytes = "0.4.12"
bitvec = "0.10"

[dev-dependencies]
galvanic-test = "0.2"
